version: '3'
services:
  web:
    build: .
    ports:
      - "5500:80"
    env_file: .env
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/auth-server
      - PORT=80   
      - DEBUG=*
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data:/var/lib/postgresql/data
      - ./docker/scripts:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=auth-server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
