-- SQL Schema
CREATE TABLE apps (
	reference VARCHAR,
	domain VARCHAR,
	client_id VARCHAR(2000) NOT NULL PRIMARY KEY,
	client_secret VARCHAR(2000) NOT NULL,SLEE
	admin_id VARCHAR(2000) NOT NULL,
	guid VARCHAR UNIQUE DEFAULT MD5(CAST(RANDOM() AS VARCHAR))
);